// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CadastroLivroTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cadastroLivro() {
    // Test name: CadastroLivro
    // Step # | name | target | value
    // 1 | open | /sig/livro | 
    driver.get("https://ts-scel-web.herokuapp.com/sig/livro");
    // 2 | click | id=isbn | 
    driver.findElement(By.id("isbn")).click();
    // 3 | type | id=isbn | 1234
    driver.findElement(By.id("isbn")).sendKeys("1234");
    // 4 | click | id=autor | 
    driver.findElement(By.id("autor")).click();
    // 5 | type | id=autor | Machado de Assis
    driver.findElement(By.id("autor")).sendKeys("Machado de Assis");
    // 6 | type | id=titulo | Dom Casmurro
    driver.findElement(By.id("titulo")).sendKeys("Dom Casmurro");
    // 7 | click | css=.btn:nth-child(1) | 
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
  }
}
