// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditaLivroSemValidaoIDTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void editaLivroSemValidaoID() {
    // Test name: EditaLivro - Sem Validação ID
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://ts-scel-web.herokuapp.com/");
    // 2 | setWindowSize | 968x1020 | 
    driver.manage().window().setSize(new Dimension(968, 1020));
    // 3 | click | linkText=Livros | 
    driver.findElement(By.linkText("Livros")).click();
    // 4 | click | linkText=Lista de Livros | 
    driver.findElement(By.linkText("Lista de Livros")).click();
    // 5 | click | css=tr:nth-child(2) .btn-primary | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn-primary")).click();
    // 6 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 7 | type | id=autor | Mark Anthony
    driver.findElement(By.id("autor")).sendKeys("Mark Anthony");
    // 8 | click | id=titulo | 
    driver.findElement(By.id("titulo")).click();
    // 9 | type | id=titulo | Roman Anthologies
    driver.findElement(By.id("titulo")).sendKeys("Roman Anthologies");
    // 10 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
